feat: support for php 8 style Test attribute
psalm/psalm-plugin-phpunit pull request #145
Opened 2024-05-04 15:51 UTC by lotyp

Adds support for PHPUnit `#[Test]` attribute

Closes: #144

2024-05-04 17:53 UTC, weirdan requested changes

2024-05-04 17:53 UTC, weirdan commented on src/Hooks/TestCaseHandler.php
> +                foreach ($attr_group->attrs as $attr) {
There's a `$method_storage->attributes` property that contains the attributes as Psalm understood them. For example, it (should) include attributes from stub files. Thus it's better to use that rather than low-level PHPParser stuff.

2024-05-04 17:59 UTC, weirdan commented
Also please add the variant with `#[Test]` into this test case: https://github.com/psalm/psalm-plugin-phpunit/blob/e344eaaa27871e79c6cb97b9efe52a735f9d1966/tests/acceptance/TestCase.feature#L527-L548

2025-03-31 11:27 UTC, danog commented
Implemented

2025-03-31 11:27 UTC, closed without merging